-- HMS schema (PostgreSQL / Supabase). Money is integer baht (no satang).
-- Timestamps are timestamptz (UTC); reports localize to Asia/Bangkok.
-- Booleans are kept as INTEGER 0/1 to match the application layer.

-- ---------------------------------------------------------------------------
-- Users & roles
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT    NOT NULL UNIQUE,
  password_hash TEXT    NOT NULL,
  role          TEXT    NOT NULL CHECK (role IN ('manager', 'staff')),
  display_name  TEXT    NOT NULL,
  active        INTEGER NOT NULL DEFAULT 1,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Rooms (seeded A1..A10, B1..B10)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rooms (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  building           TEXT    NOT NULL CHECK (building IN ('A', 'B')),
  number             INTEGER NOT NULL,
  label              TEXT    NOT NULL UNIQUE,
  status             TEXT    NOT NULL DEFAULT 'available'
                             CHECK (status IN ('available', 'occupied')),
  cleaning_status    TEXT    NOT NULL DEFAULT 'clean'
                             CHECK (cleaning_status IN ('clean', 'dirty', 'cleaning')),
  current_booking_id INTEGER,
  order_token        TEXT    NOT NULL,
  UNIQUE (building, number)
);

-- ---------------------------------------------------------------------------
-- Bookings
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bookings (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id              INTEGER NOT NULL REFERENCES rooms(id),
  type                 TEXT    NOT NULL CHECK (type IN ('short', 'overnight')),
  license_plate        TEXT,
  province             TEXT,
  check_in_at          TIMESTAMPTZ NOT NULL,
  expected_checkout_at TIMESTAMPTZ NOT NULL,
  actual_checkout_at   TIMESTAMPTZ,
  base_amount          INTEGER NOT NULL DEFAULT 0,
  extension_hours      INTEGER NOT NULL DEFAULT 0,
  extension_amount     INTEGER NOT NULL DEFAULT 0,
  early_checkin_fee    INTEGER NOT NULL DEFAULT 0,
  converted_overnight  INTEGER NOT NULL DEFAULT 0,
  room_total           INTEGER NOT NULL DEFAULT 0,
  status               TEXT    NOT NULL DEFAULT 'active'
                               CHECK (status IN ('active', 'closed', 'void')),
  created_by           INTEGER NOT NULL REFERENCES users(id),
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at            TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_created ON bookings(created_at);

CREATE TABLE IF NOT EXISTS booking_extensions (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id  INTEGER NOT NULL REFERENCES bookings(id),
  hours       INTEGER NOT NULL,
  amount      INTEGER NOT NULL,
  created_by  INTEGER NOT NULL REFERENCES users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Products (supplementary items)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name     TEXT    NOT NULL,
  price    INTEGER NOT NULL,
  category TEXT    NOT NULL DEFAULT 'ทั่วไป',
  active   INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS sale_items (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id  INTEGER REFERENCES bookings(id),
  product_id  INTEGER NOT NULL REFERENCES products(id),
  name        TEXT    NOT NULL,
  qty         INTEGER NOT NULL,
  unit_price  INTEGER NOT NULL,
  line_total  INTEGER NOT NULL,
  source      TEXT    NOT NULL DEFAULT 'staff' CHECK (source IN ('staff', 'customer')),
  created_by  INTEGER REFERENCES users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sale_items_booking ON sale_items(booking_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_created ON sale_items(created_at);

-- ---------------------------------------------------------------------------
-- Customer self-order queue
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customer_orders (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id     INTEGER NOT NULL REFERENCES rooms(id),
  booking_id  INTEGER REFERENCES bookings(id),
  status      TEXT    NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending', 'accepted', 'done', 'rejected')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  handled_by  INTEGER REFERENCES users(id),
  handled_at  TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS customer_order_items (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    INTEGER NOT NULL REFERENCES customer_orders(id),
  product_id  INTEGER NOT NULL REFERENCES products(id),
  name        TEXT    NOT NULL,
  qty         INTEGER NOT NULL,
  unit_price  INTEGER NOT NULL
);

-- ---------------------------------------------------------------------------
-- Shifts / cash drawer (defined before payments — payments FKs to shifts)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shifts (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_date TEXT    NOT NULL,
  opening_float INTEGER NOT NULL DEFAULT 0,
  opened_by     INTEGER NOT NULL REFERENCES users(id),
  opened_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  closing_count INTEGER,
  expected_cash INTEGER,
  variance      INTEGER,
  status        TEXT    NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  closed_by     INTEGER REFERENCES users(id),
  closed_at     TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_shifts_status ON shifts(status);

-- ---------------------------------------------------------------------------
-- Payments
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id      INTEGER REFERENCES bookings(id),
  shift_id        INTEGER REFERENCES shifts(id),
  amount          INTEGER NOT NULL,
  method          TEXT    NOT NULL CHECK (method IN ('cash', 'qr')),
  receipt_type    TEXT    NOT NULL,
  slip_image_path TEXT,
  created_by      INTEGER NOT NULL REFERENCES users(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_payments_created ON payments(created_at);
CREATE INDEX IF NOT EXISTS idx_payments_shift ON payments(shift_id);

-- ---------------------------------------------------------------------------
-- Settings + audit
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER REFERENCES users(id),
  action     TEXT    NOT NULL,
  entity     TEXT,
  entity_id  INTEGER,
  detail     TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
